-- MySQL Script generated by MySQL Workbench
-- ср, 27-чер-2018 14:46:38 +0300
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema library
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema library
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `library` DEFAULT CHARACTER SET utf8 ;
USE `library` ;

-- -----------------------------------------------------
-- Table `library`.`books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`books` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `publication_date` VARCHAR(4) NOT NULL,
  `available` INT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `library`.`authors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`authors` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(50) NOT NULL,
  `last_name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `library`.`authors_to_books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`authors_to_books` (
  `id_book` INT NOT NULL,
  `id_author` INT NOT NULL,
  `coauthor` TINYINT(1) NULL DEFAULT 0,
  INDEX `fk_author_book_1_idx` (`id_book` ASC),
  INDEX `fk_author_book_2_idx` (`id_author` ASC),
  CONSTRAINT `to_book`
    FOREIGN KEY (`id_book`)
    REFERENCES `library`.`books` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `to_author`
    FOREIGN KEY (`id_author`)
    REFERENCES `library`.`authors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `library`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(50) NOT NULL,
  `last_name` VARCHAR(50) NOT NULL,
  `date_of_birth` DATE NOT NULL,
  `registration_date` DATE NOT NULL,
  PRIMARY KEY (`id`))
COMMENT = 'formular_id';


-- -----------------------------------------------------
-- Table `library`.`records`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`records` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT NOT NULL,
  `id_book` INT NOT NULL,
  `take` DATE NOT NULL,
  `return` DATE NULL,
  `returned` TINYINT(1) NOT NULL DEFAULT 0,
  INDEX `fk_formular_1_idx` (`id_user` ASC),
  INDEX `fk_formular_2_idx` (`id_book` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `records_users`
    FOREIGN KEY (`id_user`)
    REFERENCES `library`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `records_books`
    FOREIGN KEY (`id_book`)
    REFERENCES `library`.`books` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
